import os
import shlex
import subprocess
import sys
from pathlib import Path

from ai_layer.core.config import get_settings
from ai_layer.core.paths import project_meta_dir, project_state_path
from ai_layer.core.registry import register_project
from ai_layer.privacy.service import (
    git_privacy_guard_status,
    install_git_privacy_guard,
    privacy_check,
    repository_footprint,
)


def _git(root: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", "-C", str(root), *args], capture_output=True, text=True, check=False
    )


def _private_project(tmp_path: Path, monkeypatch) -> tuple[Path, Path]:
    home = tmp_path / "home"
    project = tmp_path / "project"
    home.mkdir()
    project.mkdir()
    monkeypatch.setenv("HOME", str(home))
    monkeypatch.setenv("AI_LAYER_HOME", str(home / ".ai-layer"))
    get_settings.cache_clear()
    register_project(
        project, "private-project-id", "private", mode="strict-private", provenance="forbid"
    )
    return home, project


def test_strict_private_state_is_external_to_repository(tmp_path: Path, monkeypatch):
    home, project = _private_project(tmp_path, monkeypatch)
    try:
        meta = project_meta_dir(project)
        assert meta == (home / ".ai-layer" / "projects" / "private-project-id").resolve()
        assert project_state_path(project, "rules.md") == meta / "rules.md"
        assert project not in meta.parents and meta != project
        assert not (project / ".ai-layer").exists()
    finally:
        get_settings.cache_clear()


def test_privacy_check_blocks_provenance_but_allows_legitimate_ai_domain_content(
    tmp_path: Path, monkeypatch
):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    _git(project, "config", "user.email", "test@example.invalid")
    _git(project, "config", "user.name", "Test")
    try:
        (project / "service.py").write_text("# Generated by ChatGPT\nvalue = 1\n", encoding="utf-8")
        result = privacy_check(project)
        assert result["ok"] is False
        assert any(v["code"] == "generated-by-ai" for v in result["violations"])

        (project / "service.py").write_text(
            "# AI layer for recommendation inference\nvalue = 1\n", encoding="utf-8"
        )
        result = privacy_check(project)
        assert result["ok"] is True
    finally:
        get_settings.cache_clear()


def test_privacy_check_blocks_ai_layer_artifact_even_if_force_staged(tmp_path: Path, monkeypatch):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    try:
        artifact = project / ".ai-layer" / "project.yaml"
        artifact.parent.mkdir()
        artifact.write_text("version: 2\n", encoding="utf-8")
        _git(project, "add", "-f", ".ai-layer/project.yaml")
        result = privacy_check(project, staged=True)
        assert result["ok"] is False
        assert any(v["code"] == "ai-artifact-path" for v in result["violations"])
    finally:
        get_settings.cache_clear()


def test_repository_footprint_streams_large_tracked_text_without_false_blocker(
    tmp_path: Path, monkeypatch
):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    _git(project, "config", "user.email", "test@example.invalid")
    _git(project, "config", "user.name", "Test")
    try:
        lockfile = project / "package-lock.json"
        lockfile.write_text(
            '{"lockfileVersion": 3, "packages": {"x": "' + ("a" * 1_050_000) + '"}}\n',
            encoding="utf-8",
        )
        _git(project, "add", "package-lock.json")
        _git(project, "commit", "-m", "baseline")
        footprint = repository_footprint(project)
        assert footprint["tracked_ai_or_provenance"] == []
        assert footprint["tracked_unscannable"] == []
    finally:
        get_settings.cache_clear()


def test_repository_footprint_streams_large_tracked_text_and_detects_provenance(
    tmp_path: Path, monkeypatch
):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    _git(project, "config", "user.email", "test@example.invalid")
    _git(project, "config", "user.name", "Test")
    try:
        source = project / "large.txt"
        source.write_text(("a" * 1_050_000) + "\nGenerated by ChatGPT\n", encoding="utf-8")
        _git(project, "add", "large.txt")
        _git(project, "commit", "-m", "baseline")
        footprint = repository_footprint(project)
        assert footprint["tracked_ai_or_provenance"] == ["large.txt"]
        assert footprint["tracked_unscannable"] == []
    finally:
        get_settings.cache_clear()


def test_repository_footprint_detects_tracked_provenance(tmp_path: Path, monkeypatch):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    _git(project, "config", "user.email", "test@example.invalid")
    _git(project, "config", "user.name", "Test")
    try:
        (project / "README.md").write_text("Implemented with AI assistance.\n", encoding="utf-8")
        _git(project, "add", "README.md")
        _git(project, "commit", "-m", "baseline")
        footprint = repository_footprint(project)
        assert footprint["tracked_ai_or_provenance"] == ["README.md"]
    finally:
        get_settings.cache_clear()


def test_external_git_guard_chains_executable_legacy_hook_and_blocks_provenance(
    tmp_path: Path, monkeypatch
):
    home, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    _git(project, "config", "user.email", "test@example.invalid")
    _git(project, "config", "user.name", "Test")
    stable_bin = home / ".local" / "bin"
    stable_bin.mkdir(parents=True)
    # Stand-in CLI exercises generated hooks without importing DB/runtime dependencies.
    cli = stable_bin / "ai-layer"
    source_root = str((Path(__file__).parents[1] / "src").resolve())
    python = shlex.quote(sys.executable)
    cli.write_text(
        "#!/bin/sh\n"
        'msg=""\n'
        'if [ "${5:-}" = "--commit-message" ]; then msg="${6:-}"; fi\n'
        f'PYTHONPATH="{source_root}" {python} -c \'import sys; from ai_layer.privacy.service import privacy_check; '
        "r=privacy_check(sys.argv[1], staged=True, commit_message=(sys.argv[2] or None)); print(r); "
        'raise SystemExit(0 if r["ok"] else 1)\' "$3" "$msg"\n',
        encoding="utf-8",
    )
    cli.chmod(0o700)
    monkeypatch.setenv("PATH", str(stable_bin) + os.pathsep + os.environ.get("PATH", ""))

    legacy_log = tmp_path / "legacy.log"
    hooks_dir = Path(_git(project, "rev-parse", "--git-path", "hooks").stdout.strip())
    if not hooks_dir.is_absolute():
        hooks_dir = project / hooks_dir
    legacy = hooks_dir / "pre-commit"
    legacy.write_text(f"#!/bin/sh\necho legacy >> {legacy_log}\n", encoding="utf-8")
    legacy.chmod(0o700)
    try:
        result = install_git_privacy_guard(project)
        assert result["ready"] is True
        assert git_privacy_guard_status(project)["ready"] is True
        configured = Path(
            _git(project, "config", "--local", "--get", "core.hooksPath").stdout.strip()
        )
        assert (
            configured
            == (home / ".ai-layer" / "projects" / "private-project-id" / "git-hooks").resolve()
        )
        assert str(project) not in str(configured)
        assert "pre-commit" in result["chained_legacy_hooks"]

        (project / "bad.py").write_text("# Generated by AI\n", encoding="utf-8")
        _git(project, "add", "bad.py")
        proc = subprocess.run([str(configured / "pre-commit")], capture_output=True, text=True)
        assert proc.returncode != 0
        assert legacy_log.exists()

        _git(project, "reset")
        (project / "bad.py").unlink()
        message = tmp_path / "COMMIT_EDITMSG"
        message.write_text(
            "Normal subject\n\nCo-authored-by: ChatGPT <test@example.invalid>\n", encoding="utf-8"
        )
        proc = subprocess.run(
            [str(configured / "commit-msg"), str(message)], capture_output=True, text=True
        )
        assert proc.returncode != 0
        assert "ai-coauthor" in proc.stdout
    finally:
        get_settings.cache_clear()


def test_git_guard_reinstall_preserves_legacy_hooks(tmp_path: Path, monkeypatch):
    home, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    stable_bin = home / ".local" / "bin"
    stable_bin.mkdir(parents=True)
    cli = stable_bin / "ai-layer"
    cli.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
    cli.chmod(0o700)
    monkeypatch.setenv("PATH", str(stable_bin) + os.pathsep + os.environ.get("PATH", ""))

    legacy_log = tmp_path / "legacy-reinstall.log"
    git_dir = Path(_git(project, "rev-parse", "--git-dir").stdout.strip())
    if not git_dir.is_absolute():
        git_dir = project / git_dir
    hooks_dir = git_dir / "hooks"
    legacy = hooks_dir / "pre-commit"
    legacy.write_text(f"#!/bin/sh\necho legacy >> {legacy_log}\n", encoding="utf-8")
    legacy.chmod(0o700)
    try:
        first = install_git_privacy_guard(project)
        second = install_git_privacy_guard(project)
        assert first["ready"] is True and second["ready"] is True
        assert "pre-commit" in second["chained_legacy_hooks"]

        configured = Path(
            _git(project, "config", "--local", "--get", "core.hooksPath").stdout.strip()
        )
        proc = subprocess.run(
            [str(configured / "pre-commit")], capture_output=True, text=True, check=False
        )
        assert proc.returncode == 0
        assert legacy_log.read_text(encoding="utf-8").splitlines() == ["legacy"]
    finally:
        get_settings.cache_clear()


def test_git_guard_status_fails_closed_for_corrupt_or_non_executable_hooks(
    tmp_path: Path, monkeypatch
):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    try:
        assert install_git_privacy_guard(project)["ready"] is True
        hooks = project_state_path(project, "git-hooks")
        pre_commit = hooks / "pre-commit"
        pre_commit.chmod(0o600)
        assert git_privacy_guard_status(project)["ready"] is False

        pre_commit.chmod(0o700)
        pre_commit.write_text("#!/bin/sh\nexit 0\n", encoding="utf-8")
        assert git_privacy_guard_status(project)["ready"] is False
    finally:
        get_settings.cache_clear()


def test_git_guard_refuses_existing_custom_hooks_path(tmp_path: Path, monkeypatch):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    _git(project, "config", "--local", "core.hooksPath", "/custom/hooks")
    try:
        result = install_git_privacy_guard(project)
        assert result["ready"] is False
        assert result["conflict"] == "/custom/hooks"
        assert (
            _git(project, "config", "--local", "--get", "core.hooksPath").stdout.strip()
            == "/custom/hooks"
        )
    finally:
        get_settings.cache_clear()


def test_privacy_check_scans_renamed_destination_path(tmp_path: Path, monkeypatch):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    _git(project, "config", "user.email", "test@example.invalid")
    _git(project, "config", "user.name", "Test")
    try:
        (project / "original.py").write_text("value = 1\n", encoding="utf-8")
        _git(project, "add", "original.py")
        _git(project, "commit", "-m", "baseline")
        _git(project, "mv", "original.py", "renamed.py")
        (project / "renamed.py").write_text("# Generated by AI\nvalue = 1\n", encoding="utf-8")
        result = privacy_check(project)
        assert result["ok"] is False
        assert any(v["path"] == "renamed.py" for v in result["violations"])
    finally:
        get_settings.cache_clear()


def test_privacy_check_scans_unknown_text_extension(tmp_path: Path, monkeypatch):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    try:
        (project / "notes.custom").write_text("# Generated by ChatGPT\n", encoding="utf-8")
        _git(project, "add", "notes.custom")
        result = privacy_check(project, staged=True)
        assert result["ok"] is False
        assert any(v["code"] == "generated-by-ai" for v in result["violations"])
    finally:
        get_settings.cache_clear()


def test_privacy_check_fails_closed_for_oversized_text(tmp_path: Path, monkeypatch):
    _, project = _private_project(tmp_path, monkeypatch)
    _git(project, "init")
    try:
        (project / "large.py").write_text(
            "# Generated by ChatGPT\n" + ("x" * 1_050_000), encoding="utf-8"
        )
        _git(project, "add", "large.py")
        result = privacy_check(project, staged=True)
        assert result["ok"] is False
        assert any(v["code"] == "privacy-scan-limit" for v in result["violations"])
    finally:
        get_settings.cache_clear()


def test_strict_private_non_git_repository_fails_closed(tmp_path: Path, monkeypatch):
    _, project = _private_project(tmp_path, monkeypatch)
    try:
        (project / "bad.py").write_text("# Generated by ChatGPT\n", encoding="utf-8")
        result = privacy_check(project)
        assert result["ok"] is False
        assert result["git"] is False
        assert any(item["code"] == "git-required" for item in result["violations"])
        guard = install_git_privacy_guard(project)
        assert guard["ready"] is False
    finally:
        get_settings.cache_clear()
